from __future__ import annotations
from typing import Any, Optional, Union, Callable, Type, Literal, Generic
from pathlib import Path
import inspect

from abc import ABC, abstractmethod
from enum import *
# Внешние зависимости
from pydantic import BaseModel
from ldt import NexusStore, LDT
from attrs import define, field
from PySide6.QtWidgets import QWidget, QFormLayout, QApplication
from PySide6.QtGui import QColor, QIcon, QPixmap, QImage, QFont
from PySide6.QtCore import QObject, QSize, QEvent
from PySide6.QtQuickWidgets import QQuickWidget
from PySide6.QtQuick import QQuickItem
from PySide6.QtQml import QQmlEngine

class OWidget(APIBaseWidget, ABC):
    dumper: Any = ...
    flagsInstaller: FlagsInstaller = ...
    overlay: Optional[Overlay] = ...
    uid: Any = ...
    running: Any = ...
    mode: ModeRuns = ...
    config: Config = ...
    time_msec: Any = ...
    timer: Any = ...
    def __init__(self, config, parent = None) -> Any:
        ...
    def __ready__(self) -> Any:
        ...
    def process(self) -> Any:
        ...
    def setActive(self, state) -> Any:
        ...
    def __process__(self) -> Any:
        ...
    def reload_config(self) -> Any:
        ...
    def save_status(self) -> LDT:
        ...
    def load_status(self, status: LDT) -> Any:
        ...
    def load_config(self) -> Any:
        ...
    def gridOverlay(self, anchorX, anchorY) -> Any:
        ...
    @classmethod
    def createSettingWidget(cls, widget: 'OWidget', name_plugin: str, parent) -> Any:
        ...

class PluginSettingWidget(PluginSettingTemplate):
    formLayout: QFormLayout = ...
    def __init__(self, obj, name_plugin, parent = None) -> Any:
        ...
    def send_data(self) -> LDT:
        ...

class ModeRuns(IntEnum):
    AUTO = auto()
    VISIBLE_OVERLAY = auto()
    VISIBLE_WIDGET = auto()

class OWindow(APIBaseWidget, ABC):
    dumper: Any = ...
    overlay: Optional[Overlay] = ...
    flagsInstaller: FlagsInstaller = ...
    uid: Any = ...
    timer: Any = ...
    time_msec: Any = ...
    config: Config = ...
    box: Any = ...
    central_widget: Any = ...
    hasMoved: Any = ...
    dragging: Any = ...
    reloading: Any = ...
    offset: Any = ...
    colorize_effect: Optional[QGraphicsColorizeEffect] = ...
    def __init__(self, config, parent = None) -> Any:
        ...
    def setCentralWidget(self, widget: QWidget) -> Any:
        ...
    def __process__(self) -> Any:
        ...
    def __ready__(self) -> Any:
        ...
    def load_config(self) -> Any:
        ...
    def reload_config(self) -> Any:
        ...
    def save_status(self) -> LDT:
        ...
    def load_status(self, status: LDT) -> Any:
        ...
    def shortcut_run(self, name) -> Any:
        ...
    def toggle_input(self, state: bool) -> Any:
        ...
    def mousePressEvent(self, event) -> Any:
        ...
    def mouseMoveEvent(self, event) -> Any:
        ...
    def mouseReleaseEvent(self, event) -> Any:
        ...
    def keyPressEvent(self, event) -> Any:
        ...
    def highlightBorder(self) -> Any:
        ...
    def shortcut(self, key: str, uname: str) -> Any:
        ...
    @classmethod
    def createSettingWidget(cls, window: 'OWindow', name_plugin: str, parent) -> Any:
        ...

class PluginSettingWindow(PluginSettingTemplate):
    formLayout: QFormLayout = ...
    obj: OWindow = ...
    no_clicked: Any = ...
    moved: Any = ...
    def __init__(self, obj, name_plugin, parent = None) -> Any:
        ...
    def loader(self) -> Any:
        ...
    def send_data(self) -> LDT:
        ...

class OQMLWindow(OWindow):
    central_widget: QQuickWidget = ...
    def __init__(self, config, url, parent = None) -> Any:
        ...
    def loadQmlContent(self, url: str) -> Any:
        ...
    def _onChangeStatus(self, status) -> Any:
        ...
    def _loadPrivatePresetData(self) -> Any:
        ...
    def loadPresetData(self) -> QQmlEngine:
        ...
    def event(self, event: QEvent) -> Any:
        ...
    def getRootQml(self) -> QQuickItem:
        ...
    def setRootProperty(self, name, value) -> Any:
        ...
    def setContextProperty(self, name, value) -> Any:
        ...
    def reload_config(self) -> Any:
        ...

class ThemeController:
    loader: Any = ...
    env: Any = ...
    resource_builder: Any = ...
    app_template: Any = ...
    currentTheme: Optional[Theme] = ...
    interface: dict[str, InterfaceStyle] = ...
    widgets: dict[int, WidgetIcon] = ...
    def __init__(self) -> Any:
        ...
    def registerApp(self, app: QApplication) -> Any:
        ...
    def register(self, widget: QWidget, path: str, isEnv = True) -> Any:
        ...
    def update(self) -> Any:
        ...
    def updateUid(self, uid) -> Any:
        ...
    def updateApp(self) -> Any:
        ...
    def updateImage(self) -> Any:
        ...
    def updateAll(self) -> Any:
        ...
    def updateWidget(self, widget: QWidget | QObject) -> Any:
        ...
    def getImage(self, path: str, typeImage: str = 'pixmap', isQt = False) -> Any:
        ...
    def getPathImage(self, name) -> Any:
        ...
    def color(self, name) -> Any:
        ...
    def modulated(self, obj) -> Any:
        ...
    def setTheme(self, theme: Theme) -> Any:
        ...
    def themeName(self) -> Any:
        ...
    def registerWidget(self, widget: QWidget | QObject, path: str, nameMethod: str = 'setIcon', typeImage: str = 'pixmap', isQt = False) -> Any:
        ...

@define
class Theme(ABC):
    font: QFont = field()
    baseColor: QColor = field()
    mainTextColor: QColor = field()
    altTextColor: QColor = field()
    themeName: str = field(init=False)
    _imagePaths: dict[str, str] = field(factory=dict, init=False, repr=False)
    _iconsTheme: list[str] = field(factory=list, init=False, repr=False)
    def __attrs_pre_init__(self) -> Any:
        ...
    def __attrs_post_init__(self) -> Any:
        ...
    @property
    def base(self) -> Any:
        ...
    @property
    def mainText(self) -> Any:
        ...
    @property
    def altText(self) -> Any:
        ...
    def disabledText(self) -> Any:
        ...
    def baseInput(self) -> Any:
        ...
    def hovered(self) -> Any:
        ...
    def pressed(self) -> Any:
        ...
    def mainSelectText(self) -> Any:
        ...
    def modulateImage(self) -> Any:
        ...
    def getModulateImageQt(self, path: str, typeImage: str = 'pixmap') -> Any:
        ...
    def getModulateImage(self, path: str, typeImage: str = 'pixmap') -> Any:
        ...
    def modulated(self, obj) -> Any:
        ...
    @staticmethod
    def addFontFile(path) -> Any:
        ...
    def addImagePath(self, name, path) -> Any:
        ...
    def addIconTheme(self, path) -> Any:
        ...
    @property
    def getIconTheme(self) -> Any:
        ...
    def getImage(self, name) -> Any:
        ...
    def preInitTheme(self, *args) -> Any:
        ...
    def postInitTheme(self, *args) -> Any:
        ...

def modulatePixmap(pixmap: QPixmap, color: QColor) -> QPixmap:
    ...

def modulateImage(image: QImage, color: QColor) -> QImage:
    ...

def modulateIcon(icon: QIcon, color: QColor) -> QIcon:
    ...

class BaseHotkeyHandler(ABC):
    _callbacks: Any = ...
    _active: Any = ...
    def __init__(self) -> Any:
        ...
    def start(self) -> Any:
        ...
    def stop(self) -> Any:
        ...
    def add_hotkey(self, combo: str, callback: Callable, uname: str) -> Any:
        ...
    def remove_hotkey(self, combo, uname: str) -> Any:
        ...
    def _normalize_combo(self, combo: str) -> str:
        ...
    def _trigger_callbacks(self, combo: str) -> Any:
        ...

@define
class Config(Generic[T]):
    """Класс для управления конфигурационными файлами различных ресурсов.
Поддерживает строгую типизацию через Generics и Overloads."""
    _resource_name: str = field(alias='resource')
    _resource_type: Literal['window', 'widget', 'apps', 'setting', 'theme'] = field()
    _config_name: str = field(default='config')
    _scheme: Type[T] = field(default=None, repr=False)
    _config: T = field(init=False, repr=False)
    def __attrs_post_init__(self) -> Any:
        ...
    @staticmethod
    def getSchemeConfig(resource_type: str) -> Type[T]:
        ...
    def _load_config(self) -> T:
        ...
    @property
    def data(self) -> T:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def type(self) -> str:
        ...
    def reload(self) -> Any:
        ...
    @classmethod
    def configApplication(cls) -> Config[AppConfig]:
        ...

class CLInterface:
    cliFunction: dict[str, Callable] = ...
    @staticmethod
    def register(name = None) -> Any:
        ...
    def __init_subclass__(cls, **kwargs) -> Any:
        ...
    def namespace(self) -> Any:
        ...
    @staticmethod
    def _formatFunc(name, func: Callable, stdout) -> Any:
        ...
    def _getImplFuncRaise(self, name) -> Any:
        ...
    @staticmethod
    def _docs(obj) -> Any:
        ...
    @staticmethod
    def _convert_arg(param: inspect.Parameter, arg: str) -> Any:
        ...
    def runner(self, args: list) -> str:
        ...
    def help(self, name: str) -> Any:
        ...

class MetaCliInterface(MetaBaseWidget):
    def __new__(cls, name, bases, namespace, **extra) -> Any:
        ...

class default_configs:
    """Module-Class Stub"""
    ...

@define
class FlagsInstaller:
    _widget_ref: weakref.ReferenceType = field(repr=False)
    platform: str = field(init=False)
    window_system: str = field(init=False)
    def __attrs_post_init__(self) -> Any:
        ...
    @property
    def widget(self) -> QWidget | None:
        ...
    @classmethod
    def bind(cls, widget: QWidget) -> Any:
        ...
    def install(self, base_flags: Qt.WindowType = Qt.WindowType.Widget) -> Any:
        ...
    def set_sticky(self, enabled: bool) -> Any:
        ...
    def toggle_input_transparency(self, enabled: bool) -> Any:
        ...

def open_file_manager(path: Path) -> Any:
    ...

def getSystem() -> list[str]:
    ...

class EmitterFakeInput:
    c_keycode: Any = ...
    w_keycode: Any = ...
    l_keycode: Any = ...
    def __init__(self, c_keycode: type[BaseCommonKey], w_keycode: type[BaseWindowsKey], l_keycode: type[BaseLinuxKey]) -> Any:
        ...
    def _get_keycode_enum(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key_press(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key_release(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key(self, keycode: BaseCommonKey) -> Any:
        ...
    def isPlayingMusic(self) -> Any:
        ...

class BaseCommonKey(StrEnum):
    ...

class BaseLinuxKey(StrEnum):
    def __new__(cls, keysyms, keycode) -> Any:
        ...

class BaseWindowsKey(IntEnum):
    ...

__all__ = ['OWidget', 'PluginSettingWidget', 'ModeRuns', 'OWindow', 'PluginSettingWindow', 'OQMLWindow', 'Theme', 'ThemeController', 'modulateImage', 'modulateIcon', 'modulatePixmap', 'BaseHotkeyHandler', 'BaseLinuxKey', 'BaseWindowsKey', 'BaseCommonKey', 'EmitterFakeInput', 'CLInterface', 'MetaCliInterface', 'Config', 'default_configs', 'getSystem', 'open_file_manager']