from __future__ import annotations
from typing import Any, List, Optional, Union, Dict, Callable, Type, Literal
from pathlib import Path
import inspect

# Внешние зависимости
from pydantic import BaseModel
from PySide6.QtWidgets import QWidget, QFormLayout, QApplication
from PySide6.QtGui import QColor, QIcon, QPixmap, QImage, QFont
from PySide6.QtCore import QObject, QSize, QEvent
from PySide6.QtQuickWidgets import QQuickWidget
from PySide6.QtQuick import QQuickItem
from PySide6.QtQml import QQmlEngine

class OWidget:
    dumper: Any = ...
    def __init__(self, config, parent) -> Any:
        ...
    def __ready__(self) -> Any:
        ...
    def process(self) -> Any:
        ...
    def setActive(self, state) -> Any:
        ...
    def __process__(self) -> Any:
        ...
    def reload_config(self) -> Any:
        ...
    def save_status(self) -> LDT:
        ...
    def load_status(self, status: LDT) -> Any:
        ...
    def load_config(self) -> Any:
        ...
    def gridOverlay(self, anchorX, anchorY) -> Any:
        ...
    @classmethod
    def createSettingWidget(cls, widget: 'OWidget', name_plugin: str, parent) -> Any:
        ...

class PluginSettingWidget:
    formLayout: QFormLayout = ...
    def __init__(self, obj, name_plugin, parent) -> Any:
        ...
    def send_data(self) -> Any:
        ...

class OWindow:
    dumper: Any = ...
    def __init__(self, config, parent) -> Any:
        ...
    def setCentralWidget(self, widget: QWidget) -> Any:
        """Эмуляция QMainWindow для удобства плагинописцев"""
        ...
    def __process__(self) -> Any:
        ...
    def __ready__(self) -> Any:
        ...
    def load_config(self) -> Any:
        ...
    def reload_config(self) -> Any:
        ...
    def save_status(self) -> LDT:
        ...
    def load_status(self, status: LDT) -> Any:
        ...
    def shortcut_run(self, name) -> Any:
        ...
    def toggle_input(self, state: bool) -> Any:
        """Меняем флаги только если они реально отличаются"""
        ...
    def mousePressEvent(self, event) -> Any:
        ...
    def mouseMoveEvent(self, event) -> Any:
        ...
    def mouseReleaseEvent(self, event) -> Any:
        ...
    def keyPressEvent(self, event) -> Any:
        ...
    def highlightBorder(self) -> Any:
        ...
    def shortcut(self, key: str, uname: str) -> Any:
        ...
    @classmethod
    def createSettingWidget(cls, window: 'OWindow', name_plugin: str, parent) -> Any:
        ...

class PluginSettingWindow:
    formLayout: QFormLayout = ...
    obj: OWindow = ...
    def __init__(self, obj, name_plugin, parent) -> Any:
        ...
    def loader(self) -> Any:
        ...
    def send_data(self) -> Any:
        ...

class OQMLWindow:
    central_widget: QQuickWidget = ...
    def __init__(self, config, url, parent) -> Any:
        ...
    def loadQmlContent(self, url: str) -> Any:
        ...
    def _onChangeStatus(self, status) -> Any:
        ...
    def _loadPrivatePresetData(self) -> Any:
        """Безопасно прокидываем цвета в QML"""
        ...
    def loadPresetData(self) -> QQmlEngine:
        ...
    def event(self, event: QEvent) -> Any:
        ...
    def getRootQml(self) -> QQuickItem:
        ...
    def setRootProperty(self, name, value) -> Any:
        ...
    def setContextProperty(self, name, value) -> Any:
        ...
    def reloadConfig(self) -> Any:
        ...

class ThemeController:
    @staticmethod
    def __opacity(color: QColor, value: int) -> Any:
        ...
    @staticmethod
    def __color(color: QColor) -> Any:
        ...
    def __image(self, name) -> Any:
        ...
    def __init__(self) -> Any:
        ...
    def registerApp(self, app: QApplication) -> Any:
        ...
    def register(self, widget: QWidget, path: str, isEnv) -> Any:
        ...
    def update(self) -> Any:
        ...
    def updateUid(self, uid) -> Any:
        ...
    def updateApp(self) -> Any:
        ...
    def updateImage(self) -> Any:
        ...
    def updateAll(self) -> Any:
        ...
    def updateWidget(self, widget: QWidget | QObject) -> Any:
        ...
    def getImage(self, path: str, typeImage: str, isQt) -> Any:
        ...
    def getPathImage(self, name) -> Any:
        ...
    def color(self, name) -> Any:
        ...
    def modulated(self, obj) -> Any:
        ...
    def setTheme(self, theme: Theme) -> Any:
        ...
    def themeName(self) -> Any:
        ...
    def registerWidget(self, widget: QWidget | QObject, path: str, nameMethod: str, typeImage: str, isQt) -> Any:
        ...

class Theme:
    font: QFont = ...
    baseColor: QColor = ...
    mainTextColor: QColor = ...
    altTextColor: QColor = ...
    themeName: str = ...
    _imagePaths: dict[str, str] = ...
    _iconsTheme: list[str] = ...
    def __attrs_pre_init__(self) -> Any:
        ...
    def __attrs_post_init__(self) -> Any:
        ...
    @property
    def base(self) -> Any:
        ...
    @property
    def mainText(self) -> Any:
        ...
    @property
    def altText(self) -> Any:
        ...
    def disabledText(self) -> Any:
        ...
    def baseInput(self) -> Any:
        ...
    def hovered(self) -> Any:
        ...
    def pressed(self) -> Any:
        ...
    def mainSelectText(self) -> Any:
        ...
    def modulateImage(self) -> Any:
        ...
    def getModulateImageQt(self, path: str, typeImage: str) -> Any:
        ...
    def getModulateImage(self, path: str, typeImage: str) -> Any:
        ...
    def modulated(self, obj) -> Any:
        ...
    @staticmethod
    def addFontFile(path) -> Any:
        ...
    def addImagePath(self, name, path) -> Any:
        ...
    def addIconTheme(self, path) -> Any:
        ...
    @property
    def getIconTheme(self) -> Any:
        ...
    def getImage(self, name) -> Any:
        ...
    def preInitTheme(self) -> Any:
        ...
    def postInitTheme(self) -> Any:
        ...

def modulatePixmap(pixmap: QPixmap, color: QColor) -> QPixmap:
    """Modulates (tints) a QPixmap with the specified color while preserving alpha channel.

Args:
    pixmap: The pixmap to be tinted
    color: The color to apply

Returns:
    A new QPixmap with the color applied"""
    ...

def modulateImage(image: QImage, color: QColor) -> QImage:
    """Modulates (tints) a QImage with the specified color while preserving alpha channel.

Args:
    image: The image to be tinted
    color: The color to apply

Returns:
    A new QImage with the color applied"""
    ...

def modulateIcon(icon: QIcon, color: QColor) -> QIcon:
    """Modulates (tints) a QIcon with the specified color while preserving alpha channel.

Args:
    icon: The icon to be tinted
    color: The color to apply

Returns:
    A new QIcon with the color applied"""
    ...

class BaseHotkeyHandler:
    def __init__(self) -> Any:
        ...
    def start(self) -> Any:
        """Запускает обработчик горячих клавиш."""
        ...
    def stop(self) -> Any:
        """Останавливает обработчик."""
        ...
    def add_hotkey(self, combo: str, callback: Callable, uname: str) -> Any:
        """Потокобезопасное добавление горячей клавиши."""
        ...
    def remove_hotkey(self, combo, uname: str) -> Any:
        """Потокобезопасное удаление горячей клавиши."""
        ...
    def _normalize_combo(self, combo: str) -> str:
        """Приводит комбинацию к единому формату (lowercase, sorted)."""
        ...
    def _trigger_callbacks(self, combo: str) -> Any:
        """Вызывает все обработчики для комбинации."""
        ...

class Config:
    """Класс для управления конфигурационными файлами различных ресурсов (окна, виджеты, приложения и др.).

Загружает настройки из TOML‑файлов согласно типу ресурса и схеме конфигурации.
Поддерживает автоматическое создание дефолтных конфигураций при отсутствии файла."""
    _resource_name: str = ...
    _resource_type: Literal['window', 'widget', 'apps', 'setting', 'theme'] = ...
    _config_name: str = ...
    _scheme: Type[BaseConfig] = ...
    _config: BaseConfig = ...
    def __attrs_post_init__(self) -> Any:
        """Вызывается после инициализации атрибутов.
    
    Устанавливает схему конфигурации (если не задана) и загружает настройки из файла."""
        ...
    @staticmethod
    def getSchemeConfig(resource_type) -> Type[BaseConfig]:
        """Возвращает класс схемы конфигурации для указанного типа ресурса.
    
    :param resource_type: Тип ресурса ("window", "widget", "apps", "theme", "setting").
    :type resource_type: str
    :return: Класс схемы (подкласс BaseConfig).
    :rtype: type[BaseConfig]
    :raises TypeError: Если `resource_type` не поддерживается."""
        ...
    def _load_config(self) -> BaseConfig:
        """Загружает конфигурацию из файла согласно типу ресурса.
    
    Если файл не найден (для типа "apps"), создаёт его с дефолтными значениями.
    При ошибках вывода использует дефолтную схему.
    
    :return: Экземпляр конфигурации, соответствующий схеме `_scheme`.
    :rtype: BaseConfig
    :raises FileNotFoundError: Если файл не найден (кроме случая "apps").
    :raises Exception: Для любых других ошибок (выводится через traceback)."""
        ...
    @property
    def data(self) -> BaseConfig:
        """Возвращает копию текущей конфигурации.
    
    :return: Экземпляр конфигурации (копия).
    :rtype: BaseConfig"""
        ...
    @property
    def name(self) -> str:
        """Возвращает имя ресурса.
    
    :return: Значение `_resource_name`.
    :rtype: str"""
        ...
    @property
    def type(self) -> str:
        """Возвращает тип ресурса.
    
    :return: Значение `_resource_type`.
    :rtype: str"""
        ...
    def reload(self) -> Any:
        """Перезагружает конфигурацию из файла, обновляя `_config`.
    
    Использует `_load_config()` для повторного чтения данных."""
        ...
    @classmethod
    def configApplication(cls) -> 'Config':
        """Создаёт экземпляр конфигурации для приложения с предустановленными параметрами.
    
    :return: Объект `Config` с `_resource_name="Overlay"` и `_resource_type="apps"`.
    :rtype: Config"""
        ...

class CLInterface:
    cliFunction: dict[str, Callable] = ...
    @staticmethod
    def register(name) -> Any:
        ...
    def __init_subclass__(cls) -> Any:
        ...
    def namespace(self) -> Any:
        ...
    @staticmethod
    def _formatFunc(name, func: Callable, stdout) -> Any:
        ...
    def _getImplFuncRaise(self, name) -> Any:
        ...
    @staticmethod
    def _docs(obj) -> Any:
        ...
    @staticmethod
    def _convert_arg(param: inspect.Parameter, arg: str) -> Any:
        """Конвертирует аргумент в тип, указанный в аннотации параметра"""
        ...
    def runner(self, args: list) -> str:
        ...
    def help(self, name: str) -> Any:
        """Полная документация по методу"""
        ...

class MetaCliInterface:
    def __new__(cls, name, bases, namespace) -> Any:
        ...

class default_configs:
    """Module-Class Stub"""
    class BaseConfig:
        @classmethod
        def from_toml(cls, toml_data: str) -> Any:
            ...
    class CommonConfig:
        metadata: MetaData = ...
        def tuple_version(self) -> Any:
            ...
        def dict_version(self) -> Any:
            ...
    class MetaData:
        name: str = ...
        version: str = ...
        author: str = ...
        description: str = ...
    class AppConfig:
        ...
    class PluginConfig:
        settings: Settings = ...
    class ThemeConfig:
        palette: Palette = ...
    class OAddonsConfig:
        platform: Platform = ...

def open_file_manager(path: Path) -> Any:
    ...

def getSystem() -> list[str]:
    """Возвращает кортеж с информацией о платформе и оконной системе.

Возвращает:
    tuple[str, str]: (platform, windowSystem)
    - platform: 'linux', 'win32', 'darwin' и т.д.
    - windowSystem: 'wayland', 'x11', 'native', 'proton' или '' (если неизвестно)"""
    ...

class EmitterFakeInput:
    def __init__(self, c_keycode: type[BaseCommonKey], w_keycode: type[BaseWindowsKey], l_keycode: type[BaseLinuxKey]) -> Any:
        ...
    def _get_keycode_enum(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key_press(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key_release(self, keycode: BaseCommonKey) -> Any:
        ...
    def send_key(self, keycode: BaseCommonKey) -> Any:
        ...
    def isPlayingMusic(self) -> Any:
        ...

class BaseCommonKey:
    ...

class BaseLinuxKey:
    def __new__(cls, keysyms, keycode) -> Any:
        ...

class BaseWindowsKey:
    ...

__all__ = ['OWidget', 'PluginSettingWidget', 'OWindow', 'PluginSettingWindow', 'OQMLWindow', 'Theme', 'ThemeController', 'modulateImage', 'modulateIcon', 'modulatePixmap', 'BaseHotkeyHandler', 'BaseLinuxKey', 'BaseWindowsKey', 'BaseCommonKey', 'EmitterFakeInput', 'CLInterface', 'MetaCliInterface', 'Config', 'default_configs', 'getSystem', 'open_file_manager']